<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class NomorSQL extends Model
{
		protected $connection = 'SPL';
    // protected $primaryKey = 'id';
    protected $table = 'DBNOMOR';
    protected $fillable = array(
			'BKK',
			'NOBKK',
			'BKM',
			'NOBKM',
			'BBM',
			'NOBBM',
			'BBK',
			'NOBBK',
			'BMM',
			'NOBMM',
			'BJK',
			'NOBJK',
			'PJL',
			'NoPJL',
			'PBL',
[NOPBL] [varchar](25) NULL,
[BPPB] [varchar](5) NOT NULL,
[NOBPPB] [varchar](25) NULL,
[BPSB] [varchar](5) NULL,
[NOBPSB] [varchar](25) NULL,
[BBP] [varchar](5) NULL,
[NOBBP] [varchar](25) NULL,
[BPB] [varchar](5) NOT NULL,
[NOBPB] [varchar](25) NULL,
[SPRK] [varchar](5) NOT NULL,
[NOSPRK] [varchar](25) NULL,
[BSPRK] [varchar](5) NOT NULL,
[NOBSPRK] [varchar](25) NULL,
[PPL] [varchar](5) NOT NULL,
[NOPPL] [varchar](25) NULL,
[BPL] [varchar](5) NOT NULL,
[NOBPL] [varchar](25) NULL,
[PO] [varchar](5) NOT NULL,
[NOPO] [varchar](25) NULL,
[BPO] [varchar](5) NOT NULL,
[NOBPO] [varchar](25) NULL,
[BP] [varchar](5) NOT NULL,
[NOBP] [varchar](25) NULL,
[BPSPRK] [varchar](5) NOT NULL,
[NOBPSPRK] [varchar](25) NULL,
[INS] [varchar](5) NOT NULL,
[NOINS] [varchar](25) NULL,
[KNS] [varchar](5) NOT NULL,
[NOKNS] [varchar](25) NULL,
[RPB] [varchar](5) NOT NULL,
[NORPB] [varchar](25) NULL,
[SPG] [varchar](5) NOT NULL,
[NOSPG] [varchar](25) NULL,
[OPN] [varchar](5) NOT NULL,
[NOOPN] [varchar](25) NULL,
[KMS] [varchar](5) NOT NULL,
[NOKMS] [varchar](25) NULL,
[RBPB] [varchar](5) NOT NULL,
[NORBPB] [varchar](25) NULL,
[ENQ] [varchar](5) NOT NULL,
[NOENQ] [varchar](25) NULL,
[CR] [varchar](5) NOT NULL,
[NOCR] [varchar](25) NULL,
[SO] [varchar](5) NOT NULL,
[NOSO] [varchar](25) NULL,
[RKL] [varchar](5) NOT NULL,
[NORKL] [varchar](25) NULL,
[SC] [varchar](5) NOT NULL,
[NOSC] [varchar](25) NULL,
[SPP] [varchar](5) NOT NULL,
[NOSPP] [varchar](25) NULL,
[SPB] [varchar](5) NOT NULL,
[NOSPB] [varchar](25) NULL,
[RSPB] [varchar](5) NOT NULL,
[NORSPB] [varchar](25) NULL,
[INV] [varchar](5) NOT NULL,
[NOINV] [varchar](25) NULL,
[PNJ] [varchar](5) NOT NULL,
[NOPNJ] [varchar](25) NULL,
[TRC] [varchar](5) NOT NULL,
[NOTRC] [varchar](25) NULL,
[SHIP] [varchar](5) NOT NULL,
[NOSHIP] [varchar](25) NULL,
[TBJ] [varchar](5) NOT NULL,
[NOTBJ] [varchar](25) NULL,
[RBJ] [varchar](5) NOT NULL,
[NORBJ] [varchar](25) NULL,
[TRS] [varchar](5) NOT NULL,
[NOTRS] [varchar](25) NULL,
[AKM] [varchar](5) NOT NULL,
[RPJ] [varchar](5) NOT NULL,
[NORPJ] [varchar](25) NULL,
[BHN] [varchar](5) NOT NULL,
[NOBHN] [varchar](25) NULL,
[ALIAS] [varchar](5) NOT NULL,
[PEMISAH] [varchar](1) NOT NULL,
[FORMAT1] [tinyint] NOT NULL,
[FORMAT2] [tinyint] NOT NULL,
[FORMAT3] [tinyint] NOT NULL,
[FORMAT4] [tinyint] NOT NULL,
[Contoh] [varchar](20) NOT NULL,
[Reset] [tinyint] NOT NULL,
[NOSERI] [varchar](50) NOT NULL,
[INICAB] [varchar](4) NOT NULL,
[DigitNomor] [varchar](10) NOT NULL,
[SPK] [varchar](3) NULL,
[RBP] [varchar](3) NULL,
[PR] [varchar](2) NULL,
[DN] [varchar](2) NULL,
[OPBJ] [varchar](4) NULL,
[KMBJ] [varchar](4) NULL,
[INVC] [varchar](5) NULL,
[NoINVC] [varchar](25) NULL,
[SPR] [varchar](5) NULL,
[NoSPR] [varchar](25) NULL,
[KN] [varchar](5) NULL,
[NoKN] [varchar](25) NULL,
[HPD] [varchar](3) NULL,
[PBS] [varchar](5) NOT NULL,
[RPBS] [varchar](5) NOT NULL,
[POS] [varchar](25) NULL,
[HT] [varchar](10) NULL,
[PT] [varchar](5) NULL,
[TT] [varchar](5) NULL,
[KRS] [varchar](5) NOT NULL,
[DPH] [varchar](3) NULL,
[DPP] [varchar](3) NULL,
[BGT] [varchar](5) NULL,
[BGC] [varchar](5) NULL,
[BBG] [varchar](5) NULL,
[BCG] [varchar](5) NULL,
[PRJ] [varchar](5) NULL,
[UMJ] [varchar](5) NULL,
[PRB] [varchar](5) NULL,
[TDP] [varchar](5) NULL,
[PRA] [varchar](5) NULL,
[UMB] [varchar](5) NULL,
[RJC] [varchar](5) NULL,
[PRS] [varchar](5) NULL,
SSP
				'reset'
    );
    public $timestamps = false;
}

?>
