name: aplikasi_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0
  intl: ^0.19.0
  sliding_up_panel: ^2.0.0+1
  http: ^1.2.2
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  flutter_polyline_points: ^2.1.0
  permission_handler: ^11.0.0
  geolocator: ^11.0.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  network_info_plus: ^6.1.4
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
